version: '3.8'
services:
  db:
    build: .
    ports:
      - "5432:5432"

  api:
    build: ./api
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/db_survey
      SPRING_DATASOURCE_USERNAME: ungabunga
      SPRING_DATASOURCE_PASSWORD: 1111

  service:
    build: ./service
    ports:
      - "8081:8081"
    depends_on:
      - api
    environment:
      SURVEYAGREGATOR_API: http://api:8080